# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# --- Build Stage ---
FROM golang:1.24-alpine AS builder

# Install git for module fetching
RUN apk add --no-cache git ca-certificates

WORKDIR /app

# Cache module dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the MCP server
RUN go build -o bin/server

# --- Final Stage ---
FROM alpine:latest

# Add certificates if any external calls are made
RUN apk add --no-cache ca-certificates
WORKDIR /app

# Copy built binary
COPY --from=builder /app/bin/server ./bin/server

# Ensure executable permissions
RUN chmod +x ./bin/server

# Default entrypoint
ENTRYPOINT ["./bin/server"]
